# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87fbb647d07caa67a27270ab5825d5e2"
name = "discount-bxgy-adn"
handle = "discount-bxgy-adn"
application_url = "https://requires-wearing-neil-larger.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "my-store-development-14.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_draft_orders"

[auth]
redirect_urls = [
  "https://requires-wearing-neil-larger.trycloudflare.com/auth/callback",
  "https://requires-wearing-neil-larger.trycloudflare.com/auth/shopify/callback",
  "https://requires-wearing-neil-larger.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
